new: C_constants C_constants.c escape escape.c headadd if_usb if_wlan natap prbs python_test_scope task2do unescape unescape.c utorrent modified: abbr backup cmdsed diffdir eps2png game_tossdicestatistics keydetect lightlocker listmisc math pathpart pdf2png plot w3 delete: fftspec.gp fftspeceps.gp fftspecpdf.gp fftspecprint.gp mkdircd test

diff --git a/math b/math
--- a/math
+++ b/math
@@ -1,4 +1,11 @@
 #!/bin/bash
+VERSION="0-1"
+PROGNAME=$(basename $BASH_SOURCE)
+usage(){
+    echo "SYNOPSIS:"
+    echo "  $PROGNAME d2b|b2h|d2o <num list>"
+}
+
 statblk(){
     # usage:
     #   IFS=':' rnn=($(statblk ${datafname}))
@@ -186,3 +193,25 @@ d2o(){
         echo "obase=8;${i}" |bc
     done
 }
+
+# parse inut
+[ $# -eq 0 ] && usage && exit 0
+[ $1 == "-h" -o "$1" == "--help" -o "$1" == "h" -o "$1" == "help" ] && usage && exit 0
+
+case "$1" in
+    d2b) 
+        shift 1
+        d2b $@
+        ;;
+    d2o)
+        shift 1
+        d2b $@
+        ;;
+    d2h)
+        shift 
+        d2h $@
+        ;;
+    *)
+        echo "invalid command $1" && usage && exit 1
+        ;;
+esac
diff --git a/pdf2png b/pdf2png
--- a/pdf2png
+++ b/pdf2png
@@ -14,13 +14,13 @@ syntax(){
     echo "Options:"
     echo "  -h, print this help"
 }
-if [ ! -x /usr/bin/gs ]; then echo "gs cannot be run.";return 1;fi
-if [ $# -gt 3 -o $# -lt 1 ]; then syntax;return 1;fi
-if [ "$1" = "-h" ]; then syntax;return 0;fi
-local ifile="${1%.pdf}.pdf"
-local ofile="${2:-${1%.pdf}}"
-local res=${3:-600}
+if [ ! -x /usr/bin/gs ]; then echo "gs cannot be run.";exit 1;fi
+if [ $# -gt 3 -o $# -lt 1 ]; then syntax;exit 1;fi
+if [ "$1" = "-h" ]; then syntax;exit 0;fi
+ifile="${1%.pdf}.pdf"
+ofile="${2:-${1%.pdf}}"
+res=${3:-600}
 ofile="${ofile%.png}.png"
-if [ ! -f "${ifile}" ]; then echo "File $ifile doesnot exist."; return 1;fi
-if [ -f "${ofile}" ]; then echo "File $ofile exists. Please give a new name.";return 1; fi
+if [ ! -f "${ifile}" ]; then echo "File $ifile doesnot exist."; exit 1;fi
+#if [ -f "${ofile}" ]; then echo "File $ofile exists. Please give a new name.";exit 1; fi
 gs -o -q -sDEVICE=png256 -dPDFCrop -r${res} -o${ofile} ${ifile} >/dev/null
